CREATE TABLE room_revenue_holds (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    room_id BIGINT UNSIGNED NOT NULL REFERENCES rooms(id),
    owner_user_id BIGINT UNSIGNED NOT NULL REFERENCES users(id),
    corporate_id BIGINT UNSIGNED NULL REFERENCES corporates(id),
    amount BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    release_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);